CREATE TABLE exam_user (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(255) NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    last_login_at   TIMESTAMP
);